#!/bin/bash

BASE_URL="ftp://ftp.ncbi.nlm.nih.gov/geo/series/"
set -x
##mkdir -p "$(dirname $target)"
bash bin/target
mkdir -p `dirname ./bin/target`
echo "Haciendo $target"
cut -d '/' -f6 index.html| sed "s#^#results/#" | sed "s#\$#.block#> results/

