< ../config.mk

all:V:

results/%/index.html: data/index.html
	echo "[DEBUGGING] Descargando indice para $stem"
	set -x
	mkdir -p `dirname $target`
	wget -q -O - $BASE_URL/$stem/ \
	| cut -d '"' -f2 \
	| grep ftp > $target.build \
	&& mv $target.build $target
