< ../config.mk

all:VQ:
##	set -x
	bin/targets | xargs mk

results/%/metadata.soft.gz:
	echo "[DEBUGGING] Descargando metadatos de $stem"
##	set -x
##	bin/targets
	mkdir -p `dirname $target`
	wget -q -O - $BASE_URL_3/$stem/*_full.soft.gz > $target.build
	mv $target.build $target
