< ../config.mk

all:VQ:
	set -x
	bin/targets | xargs mk

results/%/index.html:
	echo "[DEBUGGING] Descargando indice para $stem"
	set -x
	bin/targets
	mkdir -p `dirname $target`
	wget -q -O - $BASE_URL_3/$stem/ \
	| cut -d '"' -f2 \
	| grep ftp > $target.build \
	&& mv $target.build $target
